export { default as Home } from './Home';
export { default as Nav } from './nav/Nav';
export { default as ProfileBanner } from './profile/ProfileBanner';
export { default as Bio } from './main/Bio';
export { default as Portfolio } from './main/Portfolio';
export { default as Resume } from './main/Resume';
export { default as Contact } from './main/Contact';
export { default as Login } from './scases/Login';
export { default as PostForm } from './scases/PostForm';
